#! /bin/bash

set -e

rpmdev-setuptree
rpm -i *.src.rpm
cd ~/rpmbuild
diff -u SPECS/*.spec /bld/*.spec || true
sn=$(basename SPECS/*.spec)
rpmbuild -bb --noclean /bld/$sn
mv RPMS/x86_64/*.rpm /bld/bld
mv BUILD/djcross-*/*s.zip /bld/bld || true
