# This is a basic workflow to help you get started with Actions

name: Cross-native

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Download rpms
        run: |
          mkdir rpms
          cd rpms
          curl -O http://www.delorie.com/pub/djgpp/rpms/djcrx-2.05-5.x86_64.rpm
          curl -O http://www.delorie.com/pub/djgpp/rpms/djcross-binutils-2.34-1ap.x86_64.rpm
          curl -O https://stefanr-dump.s3.eu-west-1.amazonaws.com/djcross-gcc-10.3.0-1ap.x86_64.rpm
          curl -O https://stefanr-dump.s3.eu-west-1.amazonaws.com/djcross-gcc-c%2B%2B-10.3.0-1ap.x86_64.rpm

      - name: Docker build
        run: docker build -f Dockerfile.cross-native -t bld35:now .

      - name: Docker run
        run: chmod 777 . bld/ && docker run -v $PWD:/bld bld35:now /thescript.cross-native

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tarball
          path: bld/cross-native.tgz
